-- require('stabline').setup {
--   style = "arrow",
-- }
--
--
-- require("staline").setup({
--   mode_icons = {
--     n = "󰈈 ",
--     i = "󰏫 ",
--     c = " ",
--     v = "󰙒 ", -- etc..
--   },
--   lsp_symbols = {
--     Error = " ",
--     Info = " ",
--     Warn = " ",
--     Hint = "",
--   },
--   sections = {
--     left  = {
--       " ", "right_sep_double", "-mode", "left_sep_double", " ",
--       "right_sep", "-file_name", "left_sep", " ",
--       "right_sep_double", "-branch", "left_sep_double", " ",
--     },
--     mid   = { "lsp", },
--     right = {
--       "right_sep", "-cool_symbol", "left_sep", " ",
--       "right_sep", "- ", "-lsp_name", "- ", "left_sep", " ",
--       "right_sep_double", "-line_column", "left_sep_double", " ",
--     }
--   },
--
--   defaults = {
--     fg              = "#ecabff",
--     left_separator  = "",
--     right_separator = "",
--     true_colors     = true,
--     line_column     = "[%l:%c] ≡%p%% ",
--     mod_symbol      = "  ",
--   },
--
--   mode_colors = {
--     n = "#181a23",
--     i = "#181a23",
--     c = "#181a23",
--     v = "#181a23",
--     ic = "#181a23",
--     V = "#181a23",
--     t = "#181a23",
--     R = "#181a23",
--     r = "#181a23",
--     s = "#181a23",
--     S = "#181a23",
--   },
-- })
